version: '3.1'

networks:
  net:
    external: true

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  web:
    container_name: web
    build: .
    restart: always
    env_file:
      - .env

    volumes:
      - .:/code
    depends_on:
      - mysql
    ports:
      - "8001:8001"