# Generated by Django 3.2.7 on 2022-03-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20220323_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
