# Generated by Django 3.2.7 on 2022-03-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_userdetail_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='firstname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='guardian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='lastname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userobject',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
