# Generated by Django 3.2.7 on 2022-03-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20220323_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiclesson',
            name='stars',
        ),
    ]
