# Generated by Django 3.2.7 on 2022-03-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20220323_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='game',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='practicebadge',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='topicpractice',
            name='stars',
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, choices=[('WAIT', 'CHỜ XỬ LÝ'), ('SPAM', 'SPAM'), ('COMPLETED', 'HOÀN TẤT')], default='WAIT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='stars',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
