# Generated by Django 3.2.7 on 2022-03-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_trackingcompetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnLessonBadge',
            fields=[
                ('ownlessonbadgeid', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateField(auto_now_add=True, null=True)),
                ('editdate', models.DateTimeField(auto_now=True, null=True)),
                ('isenable', models.BooleanField(blank=True, default=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('accountid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.account')),
                ('lessonbadgeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.lessonbadge')),
            ],
            options={
                'db_table': 'OwnLessonBadge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OwnCompetitionBadge',
            fields=[
                ('ownlcompbadgeid', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateField(auto_now_add=True, null=True)),
                ('editdate', models.DateTimeField(auto_now=True, null=True)),
                ('isenable', models.BooleanField(blank=True, default=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('accountid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.account')),
                ('competitionbadgeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.competitionbadge')),
            ],
            options={
                'db_table': 'OwnCompetitionBadge',
                'managed': True,
            },
        ),
    ]
