# Generated by Django 3.2.7 on 2022-03-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_trackingcontenttest_trackingtimetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingcontenttest',
            name='timetestid',
        ),
        migrations.AddField(
            model_name='trackingcontenttest',
            name='contenttestid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.contenttest'),
        ),
        migrations.AlterField(
            model_name='trackingtimetest',
            name='timetestid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.timetest'),
        ),
    ]
