# Generated by Django 3.2.7 on 2022-04-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_activity_topiclessonid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingcompetition',
            old_name='rank',
            new_name='timedone',
        ),
    ]
