# Generated by Django 3.2.7 on 2022-04-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_rank_trackingcompetition_timedone'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionbadge',
            name='condition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competitionbadge',
            name='logo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
